# 配置RabbitMQ
spring:
  rabbitmq:
    host: 192.168.106.100
    port: 5672
    virtual-host: /
    username: admin
    password: admin
    
    listener:
      simple:
        acknowledge-mode: manual # 消费者手动确认消息模式